# Generated by Django 4.2.7 on 2025-10-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_alter_scientificfield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, max_length=150, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='profile',
            name='research_interests',
            field=models.TextField(blank=True, max_length=800, verbose_name='Научные интересы'),
        ),
    ]
