# Generated by Django 4.2.7 on 2025-10-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_education_profile_location_profile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('candidate', 'Кандидат наук'), ('doctor', 'Доктор наук'), ('professor', 'Профессор')], max_length=20, verbose_name='Ученая степень'),
        ),
    ]
