# Generated by Django 4.2.7 on 2025-10-08 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_academic_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('candidate', 'Кандидат наук'), ('doctor', 'Доктор наук'), ('professor', 'Профессор')], default='none', max_length=20, verbose_name='Ученая степень'),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='К пользователю')),
            ],
            options={
                'verbose_name': 'Запрос дружбы',
                'verbose_name_plural': 'Запросы дружбы',
                'ordering': ['-created_at'],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
