# Generated by Django 4.2.7 on 2025-10-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
        migrations.AddField(
            model_name='community',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='communities/avatars/', verbose_name='Аватар сообщества'),
        ),
        migrations.AddField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='communities/banners/', verbose_name='Баннер сообщества'),
        ),
        migrations.AddField(
            model_name='community',
            name='community_type',
            field=models.CharField(choices=[('open', 'Открытое'), ('closed', 'Закрытое'), ('private', 'Приватное')], default='open', max_length=20, verbose_name='Тип сообщества'),
        ),
        migrations.AddField(
            model_name='community',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Контактный email'),
        ),
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.TextField(blank=True, verbose_name='Правила сообщества'),
        ),
        migrations.AddField(
            model_name='community',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='community',
            name='website',
            field=models.URLField(blank=True, verbose_name='Веб-сайт'),
        ),
        migrations.AddField(
            model_name='communitymembership',
            name='role',
            field=models.CharField(choices=[('member', 'Участник'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='member', max_length=20, verbose_name='Роль'),
        ),
    ]
