# Generated by Django 4.2.7 on 2025-10-05 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paperembedding',
            options={'verbose_name': 'Эмбеддинг статьи', 'verbose_name_plural': 'Эмбеддинги статей'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AlterModelOptions(
            name='userembedding',
            options={'verbose_name': 'Эмбеддинг пользователя', 'verbose_name_plural': 'Эмбеддинги пользователей'},
        ),
        migrations.AlterField(
            model_name='paperembedding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='paperembedding',
            name='doi',
            field=models.CharField(max_length=100, unique=True, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='paperembedding',
            name='embedding_vector',
            field=models.TextField(verbose_name='Вектор эмбеддинга'),
        ),
        migrations.AlterField(
            model_name='paperembedding',
            name='scientific_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.scientificfield', verbose_name='Научная область'),
        ),
        migrations.AlterField(
            model_name='paperembedding',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to=settings.AUTH_USER_MODEL, verbose_name='Рекомендованный пользователь'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.FloatField(verbose_name='Оценка сходства'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userembedding',
            name='embedding_vector',
            field=models.TextField(verbose_name='Вектор эмбеддинга'),
        ),
        migrations.AlterField(
            model_name='userembedding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='userembedding',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
